### ISSUE TITLE
咸猫你啥时候变成屑魔女了

### ISSUE THREAD

**Issue by yuesha-yc** [GreyElaina/GreyElaina#1]
草

**Comment by GreyElaina** [comment]
主要是感觉原来的 ID 会有被爆破的嫌疑, 加上我那会在读这部作品, 就想着换了. 当然, 我还是我, 没有什么变化, 不过我在 7 月购买了 Minecraft Java Edition, 使用了是 `GreyElaina` 这个 ID, 所以请别认错.
很抱歉在 15d, 相当于半个月后才回复.

**Comment by GreyElaina** [comment]
考虑将本 repo 作为我的个人留言板.

**Comment by Zyilin98** [comment]
有种违和感
