### ISSUE TITLE
Pretty useless issue :)

### ISSUE THREAD

**Issue by ghost** [GreyElaina/GreyElaina#4]
Hello. I don't know chinese, japanese, or language, on which your "about" is wroten, and I hope, that I write to a right place. Just for a statistical survey: are you a female, and how old are you ?

**Comment by GreyElaina** [comment]
a pretty useless issue.

answers: nope; on the internet you should not tell someone else your info.

so, i will close this issue because i have many things to do.

if you donot need to read a language that you see sometimes in your life, just ignore it plz.
